name: opus_flutter_ios
description: iOS implementation of the opus_flutter plugin.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter_ios
version: 4.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  opus_flutter_platform_interface:
    path: ../opus_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
 plugin:
    implements: opus_flutter
    platforms:
      ios:
        pluginClass: OpusFlutterIosPlugin